- hosts: all
  roles:
    - role: common

- hosts: masters
  roles:
    - role: consul
    - role: nomad
    - role: vault

- hosts: workers
  roles:
    - role: consul
    - role: nomad
    - role: rkt

